version = 0.1

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
stack_name = "fastapi-lambda"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-kg1ciogfkvpj"
confirm_changeset = false
